CaixaEletronico/Models/ErrorViewModel.cs
namespace CaixaEletronico.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CaixaEletronico/Models/Notas.cs
namespace CaixaEletronico.Models
{
    public class Notas
    {
        public int NotasID { get; set; }
        public int Valor { get; set; }
        public int Quantidade { get; set; }

        public string Imagem { get; set; }
    }
}

CaixaEletronico/Models/Saque.cs
using System.ComponentModel.DataAnnotations;

namespace CaixaEletronico.Models
{
    public class Saque
    {
        [Required(ErrorMessage = "Informe o valor do saque.")]
        [Range(minimum: 1, maximum: 10000, ErrorMessage = "Valor minímo é 0 e o máximo é 10000.")]
        public int? Valor { get; set; }
    }
}

CaixaEletronico/Class/CaixaViewComponent.cs
using CaixaEletronico.Data;
using Microsoft.AspNetCore.Mvc;
using System.Linq;

namespace CaixaEletronico.Class
{

    public class CaixaViewComponent : ViewComponent
    {
        private readonly DBContext db;

        public CaixaViewComponent(DBContext context)
        {
            db = context;
        }

        public IViewComponentResult Invoke()
        {
            return View("Caixa", db.Notas.ToList());
        }
    }
}

CaixaEletronico/Controllers/HomeController.cs
using CaixaEletronico.Class;
using CaixaEletronico.Data;
using CaixaEletronico.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;

namespace CaixaEletronico.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly DBContext db;

        public HomeController(DBContext context, ILogger<HomeController> logger)
        {
            db = context;
            _logger = logger;
        }

        [HttpGet]
        public IActionResult Index()
        {

            return View();
        }

        public PartialViewResult Caixa()
        {
            return PartialView("Views/Home/Components/Caixa/Caixa.cshtml", db.Notas.ToList());
        }

        [HttpGet]
        public PartialViewResult Saque()
        {
            ViewBag.Sucesso = null;
            return PartialView();
        }

        [HttpPost]
        public PartialViewResult Saque(Saque saque)
        {
            if (saque.Valor.HasValue)
            {
                int valorInicial = saque.Valor.Value;
                int valorRestante = saque.Valor.Value;
                var caixa = db.Notas.OrderByDescending(x => x.Valor).ToList();

                List<ListNotas> notasNecessarias = new List<ListNotas>(); //Lista contendo as notas a movimentar

                foreach (var x in caixa)
                {
                    int qtdNotas = 0;

                    if (x.Quantidade > 0)
                    {
                        qtdNotas = (int)Math.Floor(valorRestante / Convert.ToDecimal(x.Valor));

                        if ((x.Quantidade - qtdNotas) < 0)
                        {
                            qtdNotas = x.Quantidade;
                        }

                        notasNecessarias.Add(new ListNotas()
                        {
                            Valor = x.Valor,
                            Quantidade = qtdNotas,
                            ValorTotal = x.Valor * qtdNotas
                        });
                        valorRestante -= (x.Valor * qtdNotas);
                    }

                }
                int valorTotalDisponivel = notasNecessarias.Sum(x => x.ValorTotal);
                string mensagem;
                mensagem = $"Valor [{valorInicial:C2}] não disponivél.";
                if (valorTotalDisponivel < valorInicial && valorTotalDisponivel > 0)
                {
                    mensagem += $" Tente[{ valorTotalDisponivel:C2}]";
                    int totalCaixa = caixa.Sum(x => x.Quantidade * x.Valor);
                    foreach (var x in caixa.OrderBy(x => x.Valor))
                    {
                        int notas = notasNecessarias.Where(a => a.Valor == x.Valor).FirstOrDefault().Quantidade;
                        if ((x.Quantidade - notas) > 0)
                        {
                            mensagem += $" ou [{valorTotalDisponivel + x.Valor:C2}]";
                        }

                    }
                    mensagem += ".";

                    ModelState.AddModelError("Valor", mensagem);
                }

                if (ModelState.IsValid)
                {
                    try
                    {
                        foreach (var x in notasNecessarias)
                        {
                            if (x.Quantidade > 0)
                            {
                                Notas notas = db.Notas.Where(a => a.Valor == x.Valor).FirstOrDefault();

                                notas.Quantidade += -x.Quantidade;

                                db.SaveChanges();
                            }

                        }
                        ViewBag.Sucesso = $"Saque do valor [{valorTotalDisponivel:C2}] realizado com sucesso!";
                    }
                    catch (Exception ex)
                    {
                        ViewBag.Sucesso = null;
                        ModelState.AddModelError("Valor", "Ocorreu um erro ao salvar os dados.");
                    }


                    return PartialView(saque);
                }
            }





            return PartialView(saque);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CaixaEletronico/Views/Home/Components/Caixa/Caixa.cshtml
@model IEnumerable<CaixaEletronico.Models.Notas>
<button type="button" class="collapsible active">Overview do caixa</button>
<div class="content">

    <table class="table">
        <thead>
            <tr>
                <th style="width:40%;">
                    @Html.DisplayNameFor(model => model.Valor)
                </th>
                <th style="width:60%;">
                    @Html.DisplayNameFor(model => model.Quantidade)
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @*<i href="item.Imagem" class="notas"></i>*@
                        <img src="@Url.Content(item.Imagem)" class="notas" />
                        @*@Html.DisplayFor(modelItem => item.Valor)*@
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Quantidade)
                    </td>
                </tr>
            }
        </tbody>
    </table>
</div>

CaixaEletronico/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Saque";
    <link href="~/css/styleHome.css" type="text/css" rel="stylesheet" />
    <script src="~/js/scriptHome.js"></script>
}

<div class="jumbotron">
    <h1>Saque</h1>
</div>

<div class="row">
    <div class="col-md-8" id="replace">
        @{
            await Html.RenderPartialAsync("Saque.cshtml", new CaixaEletronico.Models.Saque());
        }
    </div>
    <div class="col-md-4" id="replaceCaixa">
        @await Component.InvokeAsync("Caixa")
    </div>
</div>

CaixaEletronico/Views/Home/Saque.cshtml
@model CaixaEletronico.Models.Saque
@{

}
<div class="jumbotron">

    <form class="form-row" asp-action="Saque" asp-controller="Home" data-ajax="true" data-ajax-method="post" data-ajax-update="#replace"
          data-ajax-success="Success">
        <div class="col-sm-12">
            <h4>Insira o valor do saque e clique em "Sacar"</h4>
        </div>
        <div class="col-sm-12">
            <div class="input-group">
                <div class="input-group-prepend">
                    <div class="input-group-text" id="btnGroupAddon2">R$</div>
                </div>
                <input type="number" min="1" name="Valor" id="money" class="form-control" placeholder="Valor do saque" aria-describedby="btnGroupAddon2">
            </div>
        </div>
        <div class="col-sm-12">
            <span asp-validation-for="Valor" class="text-danger"></span>
            @if (ViewBag.Sucesso != null)
            {
                <span class="text-info">@ViewBag.Sucesso</span>
            }
        </div>

        <br />
        <div class="col-sm-12">
            <button type="submit" class="btn btn-primary">Sacar</button>
        </div>

    </form>
</div>

<script>
    function Success() {
        $.get("Home/Caixa", function (data, status) {
            if (data.length > 0) {
                $('#replaceCaixa').html(data);
            }
        });
    }
</script>

CaixaEletronico/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Caixa Eletronico</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <script src="~/lib/jquery/jquery.min.js"></script>
    <script src="~/lib/jquery-ajax-unobtrusive/jquery.unobtrusive-ajax.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CaixaEletronico</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Saque</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - CaixaEletronico
        </div>
    </footer>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>